// IDL from CSS Object Model (CSSOM) Editor’s Draft, 8 November 2020
// https://github.com/w3c/csswg-drafts/tree/3e784aa677bde2b097409fa7b19f608c2b3c0d16

[Exposed=Window]
interface CSSStyleSheet : StyleSheet {
  readonly attribute CSSRule? ownerRule;
  [SameObject] readonly attribute CSSRuleList cssRules;
  unsigned long insertRule(CSSOMString rule, optional unsigned long index = 0);
  undefined deleteRule(unsigned long index);
};

// IDL from Constructable Stylesheet Objects A Collection of Interesting Ideas, 3 March 2020
// https://wicg.github.io/construct-stylesheets/

partial interface CSSStyleSheet {
  constructor(optional CSSStyleSheetInit options = {});
  Promise<CSSStyleSheet> replace(USVString text);
  void replaceSync(USVString text);
};

dictionary CSSStyleSheetInit {
  (MediaList or DOMString) media = "";
  DOMString title = "";
  boolean alternate = false;
  boolean disabled = false;
};
