// IDL from DOM Living Standard - December 2020
// https://github.com/whatwg/dom/blob/master/review-drafts/2020-12.bs

[Exposed=Window]
interface ShadowRoot : DocumentFragment {
  readonly attribute ShadowRootMode mode;
  readonly attribute Element host;
  attribute EventHandler onslotchange;
};

enum ShadowRootMode { "open", "closed" };
