// Generated by Rampage on 2025-02-07 07:51:13.718017

import 'package:meta/meta.dart';
import 'package:rampage_js_interop/js_interop.dart' as js;

import 'geometry.dart';
import 'wrapper.dart';

enum CSSNumericBaseType {
  length('length'),
  angle('angle'),
  time('time'),
  frequency('frequency'),
  resolution('resolution'),
  flex('flex'),
  percent('percent');

  const CSSNumericBaseType(this.toJS);

  final String toJS;
}

extension CSSNumericBaseTypeDartObject on String {
  CSSNumericBaseType get toDart => switch (this) {
    'length' => CSSNumericBaseType.length,
    'angle' => CSSNumericBaseType.angle,
    'time' => CSSNumericBaseType.time,
    'frequency' => CSSNumericBaseType.frequency,
    'resolution' => CSSNumericBaseType.resolution,
    'flex' => CSSNumericBaseType.flex,
    'percent' => CSSNumericBaseType.percent,
    _ => throw UnsupportedError('$this is not a member of CSSNumericBaseType'),
  };
}

enum CSSMathOperator {
  sum('sum'),
  product('product'),
  negate('negate'),
  invert('invert'),
  min('min'),
  max('max'),
  clamp('clamp');

  const CSSMathOperator(this.toJS);

  final String toJS;
}

extension CSSMathOperatorDartObject on String {
  CSSMathOperator get toDart => switch (this) {
    'sum' => CSSMathOperator.sum,
    'product' => CSSMathOperator.product,
    'negate' => CSSMathOperator.negate,
    'invert' => CSSMathOperator.invert,
    'min' => CSSMathOperator.min,
    'max' => CSSMathOperator.max,
    'clamp' => CSSMathOperator.clamp,
    _ => throw UnsupportedError('$this is not a member of CSSMathOperator'),
  };
}

class CSSStyleValue<T extends js.CSSStyleValue> extends DartJsWrapper<T> {
  @protected
  CSSStyleValue.fromJsObject(super.jsObject) : super.fromJsObject();
}

class StylePropertyMapReadOnly<T extends js.StylePropertyMapReadOnly>
    extends DartJsWrapper<T> {
  @protected
  StylePropertyMapReadOnly.fromJsObject(super.jsObject) : super.fromJsObject();

  int get size => jsObject.size;
}

final class StylePropertyMap
    extends StylePropertyMapReadOnly<js.StylePropertyMap> {
  StylePropertyMap.fromJsObject(super.jsObject) : super.fromJsObject();
}

final class CSSUnparsedValue extends CSSStyleValue<js.CSSUnparsedValue> {
  CSSUnparsedValue.fromJsObject(super.jsObject) : super.fromJsObject();

  int get length => jsObject.length;
}

final class CSSVariableReferenceValue
    extends DartJsWrapper<js.CSSVariableReferenceValue> {
  CSSVariableReferenceValue.fromJsObject(super.jsObject) : super.fromJsObject();

  String get variable => jsObject.variable;

  set variable(String value) {
    jsObject.variable = value;
  }

  CSSUnparsedValue? get fallback => jsObject.fallback;
}

final class CSSKeywordValue extends CSSStyleValue<js.CSSKeywordValue> {
  CSSKeywordValue.fromJsObject(super.jsObject) : super.fromJsObject();

  String get value => jsObject.value;

  set value(String value) {
    jsObject.value = value;
  }
}

class CSSNumericValue<T extends js.CSSNumericValue> extends CSSStyleValue<T> {
  @protected
  CSSNumericValue.fromJsObject(super.jsObject) : super.fromJsObject();
}

final class CSSUnitValue extends CSSNumericValue<js.CSSUnitValue> {
  CSSUnitValue.fromJsObject(super.jsObject) : super.fromJsObject();

  double get value => jsObject.value;

  set value(double value) {
    jsObject.value = value;
  }

  String get unit => jsObject.unit;
}

class CSSMathValue<T extends js.CSSMathValue> extends CSSNumericValue<T> {
  @protected
  CSSMathValue.fromJsObject(super.jsObject) : super.fromJsObject();

  CSSMathOperator get operator => jsObject.operator;
}

final class CSSMathSum extends CSSMathValue<js.CSSMathSum> {
  CSSMathSum.fromJsObject(super.jsObject) : super.fromJsObject();

  CSSNumericArray get values => jsObject.values;
}

final class CSSMathProduct extends CSSMathValue<js.CSSMathProduct> {
  CSSMathProduct.fromJsObject(super.jsObject) : super.fromJsObject();

  CSSNumericArray get values => jsObject.values;
}

final class CSSMathNegate extends CSSMathValue<js.CSSMathNegate> {
  CSSMathNegate.fromJsObject(super.jsObject) : super.fromJsObject();

  CSSNumericValue get value => jsObject.value;
}

final class CSSMathInvert extends CSSMathValue<js.CSSMathInvert> {
  CSSMathInvert.fromJsObject(super.jsObject) : super.fromJsObject();

  CSSNumericValue get value => jsObject.value;
}

final class CSSMathMin extends CSSMathValue<js.CSSMathMin> {
  CSSMathMin.fromJsObject(super.jsObject) : super.fromJsObject();

  CSSNumericArray get values => jsObject.values;
}

final class CSSMathMax extends CSSMathValue<js.CSSMathMax> {
  CSSMathMax.fromJsObject(super.jsObject) : super.fromJsObject();

  CSSNumericArray get values => jsObject.values;
}

final class CSSMathClamp extends CSSMathValue<js.CSSMathClamp> {
  CSSMathClamp.fromJsObject(super.jsObject) : super.fromJsObject();

  CSSNumericValue get lower => jsObject.lower;

  CSSNumericValue get value => jsObject.value;

  CSSNumericValue get upper => jsObject.upper;
}

final class CSSNumericArray extends DartJsWrapper<js.CSSNumericArray> {
  CSSNumericArray.fromJsObject(super.jsObject) : super.fromJsObject();

  int get length => jsObject.length;
}

final class CSSTransformValue extends CSSStyleValue<js.CSSTransformValue> {
  CSSTransformValue.fromJsObject(super.jsObject) : super.fromJsObject();

  int get length => jsObject.length;

  bool get is2D => jsObject.is2D;
}

class CSSTransformComponent<T extends js.CSSTransformComponent>
    extends DartJsWrapper<T> {
  @protected
  CSSTransformComponent.fromJsObject(super.jsObject) : super.fromJsObject();

  bool get is2D => jsObject.is2D;

  set is2D(bool value) {
    jsObject.is2D = value;
  }
}

final class CSSTranslate extends CSSTransformComponent<js.CSSTranslate> {
  CSSTranslate.fromJsObject(super.jsObject) : super.fromJsObject();

  CSSNumericValue get x => jsObject.x;

  set x(CSSNumericValue value) {
    jsObject.x = value;
  }

  CSSNumericValue get y => jsObject.y;

  set y(CSSNumericValue value) {
    jsObject.y = value;
  }

  CSSNumericValue get z => jsObject.z;

  set z(CSSNumericValue value) {
    jsObject.z = value;
  }
}

final class CSSRotate extends CSSTransformComponent<js.CSSRotate> {
  CSSRotate.fromJsObject(super.jsObject) : super.fromJsObject();

  CSSNumberish get x => jsObject.x;

  set x(CSSNumberish value) {
    jsObject.x = value;
  }

  CSSNumberish get y => jsObject.y;

  set y(CSSNumberish value) {
    jsObject.y = value;
  }

  CSSNumberish get z => jsObject.z;

  set z(CSSNumberish value) {
    jsObject.z = value;
  }

  CSSNumericValue get angle => jsObject.angle;

  set angle(CSSNumericValue value) {
    jsObject.angle = value;
  }
}

final class CSSScale extends CSSTransformComponent<js.CSSScale> {
  CSSScale.fromJsObject(super.jsObject) : super.fromJsObject();

  CSSNumberish get x => jsObject.x;

  set x(CSSNumberish value) {
    jsObject.x = value;
  }

  CSSNumberish get y => jsObject.y;

  set y(CSSNumberish value) {
    jsObject.y = value;
  }

  CSSNumberish get z => jsObject.z;

  set z(CSSNumberish value) {
    jsObject.z = value;
  }
}

final class CSSSkew extends CSSTransformComponent<js.CSSSkew> {
  CSSSkew.fromJsObject(super.jsObject) : super.fromJsObject();

  CSSNumericValue get ax => jsObject.ax;

  set ax(CSSNumericValue value) {
    jsObject.ax = value;
  }

  CSSNumericValue get ay => jsObject.ay;

  set ay(CSSNumericValue value) {
    jsObject.ay = value;
  }
}

final class CSSSkewX extends CSSTransformComponent<js.CSSSkewX> {
  CSSSkewX.fromJsObject(super.jsObject) : super.fromJsObject();

  CSSNumericValue get ax => jsObject.ax;

  set ax(CSSNumericValue value) {
    jsObject.ax = value;
  }
}

final class CSSSkewY extends CSSTransformComponent<js.CSSSkewY> {
  CSSSkewY.fromJsObject(super.jsObject) : super.fromJsObject();

  CSSNumericValue get ay => jsObject.ay;

  set ay(CSSNumericValue value) {
    jsObject.ay = value;
  }
}

final class CSSPerspective extends CSSTransformComponent<js.CSSPerspective> {
  CSSPerspective.fromJsObject(super.jsObject) : super.fromJsObject();

  CSSPerspectiveValue get length => jsObject.length;

  set length(CSSPerspectiveValue value) {
    jsObject.length = value;
  }
}

final class CSSMatrixComponent
    extends CSSTransformComponent<js.CSSMatrixComponent> {
  CSSMatrixComponent.fromJsObject(super.jsObject) : super.fromJsObject();

  DOMMatrix get matrix => jsObject.matrix;

  set matrix(DOMMatrix value) {
    jsObject.matrix = value;
  }
}

final class CSSImageValue extends CSSStyleValue<js.CSSImageValue> {
  CSSImageValue.fromJsObject(super.jsObject) : super.fromJsObject();
}

class CSSColorValue<T extends js.CSSColorValue> extends CSSStyleValue<T> {
  @protected
  CSSColorValue.fromJsObject(super.jsObject) : super.fromJsObject();
}

final class CSSRGB extends CSSColorValue<js.CSSRGB> {
  CSSRGB.fromJsObject(super.jsObject) : super.fromJsObject();

  CSSColorRGBComp get r => jsObject.r;

  set r(CSSColorRGBComp value) {
    jsObject.r = value;
  }

  CSSColorRGBComp get g => jsObject.g;

  set g(CSSColorRGBComp value) {
    jsObject.g = value;
  }

  CSSColorRGBComp get b => jsObject.b;

  set b(CSSColorRGBComp value) {
    jsObject.b = value;
  }

  CSSColorPercent get alpha => jsObject.alpha;

  set alpha(CSSColorPercent value) {
    jsObject.alpha = value;
  }
}

final class CSSHSL extends CSSColorValue<js.CSSHSL> {
  CSSHSL.fromJsObject(super.jsObject) : super.fromJsObject();

  CSSColorAngle get h => jsObject.h;

  set h(CSSColorAngle value) {
    jsObject.h = value;
  }

  CSSColorPercent get s => jsObject.s;

  set s(CSSColorPercent value) {
    jsObject.s = value;
  }

  CSSColorPercent get l => jsObject.l;

  set l(CSSColorPercent value) {
    jsObject.l = value;
  }

  CSSColorPercent get alpha => jsObject.alpha;

  set alpha(CSSColorPercent value) {
    jsObject.alpha = value;
  }
}

final class CSSHWB extends CSSColorValue<js.CSSHWB> {
  CSSHWB.fromJsObject(super.jsObject) : super.fromJsObject();

  CSSNumericValue get h => jsObject.h;

  set h(CSSNumericValue value) {
    jsObject.h = value;
  }

  CSSNumberish get w => jsObject.w;

  set w(CSSNumberish value) {
    jsObject.w = value;
  }

  CSSNumberish get b => jsObject.b;

  set b(CSSNumberish value) {
    jsObject.b = value;
  }

  CSSNumberish get alpha => jsObject.alpha;

  set alpha(CSSNumberish value) {
    jsObject.alpha = value;
  }
}

final class CSSLab extends CSSColorValue<js.CSSLab> {
  CSSLab.fromJsObject(super.jsObject) : super.fromJsObject();

  CSSColorPercent get l => jsObject.l;

  set l(CSSColorPercent value) {
    jsObject.l = value;
  }

  CSSColorNumber get a => jsObject.a;

  set a(CSSColorNumber value) {
    jsObject.a = value;
  }

  CSSColorNumber get b => jsObject.b;

  set b(CSSColorNumber value) {
    jsObject.b = value;
  }

  CSSColorPercent get alpha => jsObject.alpha;

  set alpha(CSSColorPercent value) {
    jsObject.alpha = value;
  }
}

final class CSSLCH extends CSSColorValue<js.CSSLCH> {
  CSSLCH.fromJsObject(super.jsObject) : super.fromJsObject();

  CSSColorPercent get l => jsObject.l;

  set l(CSSColorPercent value) {
    jsObject.l = value;
  }

  CSSColorPercent get c => jsObject.c;

  set c(CSSColorPercent value) {
    jsObject.c = value;
  }

  CSSColorAngle get h => jsObject.h;

  set h(CSSColorAngle value) {
    jsObject.h = value;
  }

  CSSColorPercent get alpha => jsObject.alpha;

  set alpha(CSSColorPercent value) {
    jsObject.alpha = value;
  }
}

final class CSSOKLab extends CSSColorValue<js.CSSOKLab> {
  CSSOKLab.fromJsObject(super.jsObject) : super.fromJsObject();

  CSSColorPercent get l => jsObject.l;

  set l(CSSColorPercent value) {
    jsObject.l = value;
  }

  CSSColorNumber get a => jsObject.a;

  set a(CSSColorNumber value) {
    jsObject.a = value;
  }

  CSSColorNumber get b => jsObject.b;

  set b(CSSColorNumber value) {
    jsObject.b = value;
  }

  CSSColorPercent get alpha => jsObject.alpha;

  set alpha(CSSColorPercent value) {
    jsObject.alpha = value;
  }
}

final class CSSOKLCH extends CSSColorValue<js.CSSOKLCH> {
  CSSOKLCH.fromJsObject(super.jsObject) : super.fromJsObject();

  CSSColorPercent get l => jsObject.l;

  set l(CSSColorPercent value) {
    jsObject.l = value;
  }

  CSSColorPercent get c => jsObject.c;

  set c(CSSColorPercent value) {
    jsObject.c = value;
  }

  CSSColorAngle get h => jsObject.h;

  set h(CSSColorAngle value) {
    jsObject.h = value;
  }

  CSSColorPercent get alpha => jsObject.alpha;

  set alpha(CSSColorPercent value) {
    jsObject.alpha = value;
  }
}

final class CSSColor extends CSSColorValue<js.CSSColor> {
  CSSColor.fromJsObject(super.jsObject) : super.fromJsObject();

  CSSKeywordish get colorSpace => jsObject.colorSpace;

  set colorSpace(CSSKeywordish value) {
    jsObject.colorSpace = value;
  }

  ObservableArray<CSSColorPercent> get channels => jsObject.channels;

  set channels(ObservableArray<CSSColorPercent> value) {
    jsObject.channels = value;
  }

  CSSNumberish get alpha => jsObject.alpha;

  set alpha(CSSNumberish value) {
    jsObject.alpha = value;
  }
}
