// Generated by Rampage on 2025-02-07 07:51:13.828200

import 'package:rampage_js_interop/js_interop.dart' as js;

import 'wrapper.dart';

final class ViewTransition extends DartJsWrapper<js.ViewTransition> {
  ViewTransition.fromJsObject(super.jsObject) : super.fromJsObject();

  Future<void> get updateCallbackDone => jsObject.updateCallbackDone;

  Future<void> get ready => jsObject.ready;

  Future<void> get finished => jsObject.finished;
}
