// Generated by Rampage on 2025-02-07 07:51:13.448738

import 'dart:js_interop';

import 'package:meta/meta.dart';
import 'package:rampage_js_interop/js_interop.dart' as js;

import 'css_typed_om.dart';
import 'wrapper.dart';

final class MediaList extends DartJsWrapper<js.MediaList> {
  MediaList.fromJsObject(super.jsObject) : super.fromJsObject();

  int get length => jsObject.length;
}

class StyleSheet<T extends js.StyleSheet> extends DartJsWrapper<T> {
  @protected
  StyleSheet.fromJsObject(super.jsObject) : super.fromJsObject();

  CSSOMString get type => jsObject.type;

  String? get href => jsObject.href;

  Object? get ownerNode => jsObject.ownerNode;

  CSSStyleSheet? get parentStyleSheet => jsObject.parentStyleSheet;

  String? get title => jsObject.title;

  MediaList get media => jsObject.media;

  bool get disabled => jsObject.disabled;

  set disabled(bool value) {
    jsObject.disabled = value;
  }
}

final class CSSStyleSheet extends StyleSheet<js.CSSStyleSheet> {
  CSSStyleSheet.fromJsObject(super.jsObject) : super.fromJsObject();

  CSSRule? get ownerRule => jsObject.ownerRule;

  CSSRuleList get cssRules => jsObject.cssRules;

  CSSRuleList get rules => jsObject.rules;
}

final class StyleSheetList extends DartJsWrapper<js.StyleSheetList> {
  StyleSheetList.fromJsObject(super.jsObject) : super.fromJsObject();

  int get length => jsObject.length;
}

mixin LinkStyle on DartJsWrapper<JSObject> {
  CSSStyleSheet? get sheet => jsObject.sheet;
}

final class CSSRuleList extends DartJsWrapper<js.CSSRuleList> {
  CSSRuleList.fromJsObject(super.jsObject) : super.fromJsObject();

  int get length => jsObject.length;
}

class CSSRule<T extends js.CSSRule> extends DartJsWrapper<T> {
  @protected
  CSSRule.fromJsObject(super.jsObject) : super.fromJsObject();

  CSSOMString get cssText => jsObject.cssText;

  set cssText(CSSOMString value) {
    jsObject.cssText = value;
  }

  CSSRule? get parentRule => jsObject.parentRule;

  CSSStyleSheet? get parentStyleSheet => jsObject.parentStyleSheet;

  int get type => jsObject.type;
}

final class CSSStyleRule extends CSSRule<js.CSSStyleRule> {
  CSSStyleRule.fromJsObject(super.jsObject) : super.fromJsObject();

  CSSOMString get selectorText => jsObject.selectorText;

  set selectorText(CSSOMString value) {
    jsObject.selectorText = value;
  }

  CSSStyleDeclaration get style => jsObject.style;

  StylePropertyMap get styleMap => jsObject.styleMap;
}

final class CSSImportRule extends CSSRule<js.CSSImportRule> {
  CSSImportRule.fromJsObject(super.jsObject) : super.fromJsObject();

  String get href => jsObject.href;

  MediaList get media => jsObject.media;

  CSSStyleSheet get styleSheet => jsObject.styleSheet;
}

class CSSGroupingRule<T extends js.CSSGroupingRule> extends CSSRule<T> {
  @protected
  CSSGroupingRule.fromJsObject(super.jsObject) : super.fromJsObject();

  CSSRuleList get cssRules => jsObject.cssRules;
}

final class CSSPageRule extends CSSGroupingRule<js.CSSPageRule> {
  CSSPageRule.fromJsObject(super.jsObject) : super.fromJsObject();

  CSSOMString get selectorText => jsObject.selectorText;

  set selectorText(CSSOMString value) {
    jsObject.selectorText = value;
  }

  CSSStyleDeclaration get style => jsObject.style;
}

final class CSSMarginRule extends CSSRule<js.CSSMarginRule> {
  CSSMarginRule.fromJsObject(super.jsObject) : super.fromJsObject();

  CSSOMString get name => jsObject.name;

  CSSStyleDeclaration get style => jsObject.style;
}

final class CSSNamespaceRule extends CSSRule<js.CSSNamespaceRule> {
  CSSNamespaceRule.fromJsObject(super.jsObject) : super.fromJsObject();

  CSSOMString get namespaceURI => jsObject.namespaceURI;

  CSSOMString get prefix => jsObject.prefix;
}

final class CSSStyleDeclaration extends DartJsWrapper<js.CSSStyleDeclaration> {
  CSSStyleDeclaration.fromJsObject(super.jsObject) : super.fromJsObject();

  CSSOMString get cssText => jsObject.cssText;

  set cssText(CSSOMString value) {
    jsObject.cssText = value;
  }

  int get length => jsObject.length;

  CSSRule? get parentRule => jsObject.parentRule;

  CSSOMString get cssFloat => jsObject.cssFloat;

  set cssFloat(CSSOMString value) {
    jsObject.cssFloat = value;
  }
}

mixin ElementCSSInlineStyle on DartJsWrapper<JSObject> {
  CSSStyleDeclaration get style => jsObject.style;
  StylePropertyMap get attributeStyleMap => jsObject.attributeStyleMap;
}
