// Generated by Rampage on 2025-02-07 07:51:13.868022

import 'dart:js_interop';

import 'package:meta/meta.dart';
import 'package:rampage_js_interop/js_interop.dart' as js;

import 'cssom.dart';
import 'high_resolution_time.dart';
import 'html.dart';
import 'wrapper.dart';

enum ShadowRootMode {
  open('open'),
  closed('closed');

  const ShadowRootMode(this.toJS);

  final String toJS;
}

extension ShadowRootModeDartObject on String {
  ShadowRootMode get toDart => switch (this) {
    'open' => ShadowRootMode.open,
    'closed' => ShadowRootMode.closed,
    _ => throw UnsupportedError('$this is not a member of ShadowRootMode'),
  };
}

enum SlotAssignmentMode {
  manual('manual'),
  named('named');

  const SlotAssignmentMode(this.toJS);

  final String toJS;
}

extension SlotAssignmentModeDartObject on String {
  SlotAssignmentMode get toDart => switch (this) {
    'manual' => SlotAssignmentMode.manual,
    'named' => SlotAssignmentMode.named,
    _ => throw UnsupportedError('$this is not a member of SlotAssignmentMode'),
  };
}

class Event<T extends js.Event> extends DartJsWrapper<T> {
  @protected
  Event.fromJsObject(super.jsObject) : super.fromJsObject();

  String get type => jsObject.type;

  EventTarget? get target => jsObject.target;

  EventTarget? get srcElement => jsObject.srcElement;

  EventTarget? get currentTarget => jsObject.currentTarget;

  int get eventPhase => jsObject.eventPhase;

  bool get cancelBubble => jsObject.cancelBubble;

  set cancelBubble(bool value) {
    jsObject.cancelBubble = value;
  }

  bool get bubbles => jsObject.bubbles;

  bool get cancelable => jsObject.cancelable;

  bool get returnValue => jsObject.returnValue;

  set returnValue(bool value) {
    jsObject.returnValue = value;
  }

  bool get defaultPrevented => jsObject.defaultPrevented;

  bool get composed => jsObject.composed;

  bool get isTrusted => jsObject.isTrusted;

  DOMHighResTimeStamp get timeStamp => jsObject.timeStamp;
}

final class CustomEvent extends Event<js.CustomEvent> {
  CustomEvent.fromJsObject(super.jsObject) : super.fromJsObject();

  Object get detail => jsObject.detail;
}

class EventTarget<T extends js.EventTarget> extends DartJsWrapper<T> {
  @protected
  EventTarget.fromJsObject(super.jsObject) : super.fromJsObject();
}

JsWrapper<T> safeEventTargetFromJsObject<T extends js.EventTarget>(
  T jsObject,
) => safeJsWrapperFromObject<T>(jsObject, eventTargetFromJsObject);
JsWrapper<T>? safeEventTargetFromJsObjectNullable<T extends js.EventTarget>(
  T? jsObject,
) => safeJsWrapperFromObjectNullable<T>(jsObject, eventTargetFromJsObject);

final class EventListener extends DartJsWrapper<js.EventListener> {
  EventListener.fromJsObject(super.jsObject) : super.fromJsObject();
}

final class AbortController extends DartJsWrapper<js.AbortController> {
  AbortController.fromJsObject(super.jsObject) : super.fromJsObject();

  AbortSignal get signal => jsObject.signal;
}

final class AbortSignal extends EventTarget<js.AbortSignal> {
  AbortSignal.fromJsObject(super.jsObject) : super.fromJsObject();

  bool get aborted => jsObject.aborted;

  Object get reason => jsObject.reason;

  EventHandler get onabort => jsObject.onabort;

  set onabort(EventHandler value) {
    jsObject.onabort = value;
  }
}

mixin NonElementParentNode on DartJsWrapper<JSObject> {}
mixin DocumentOrShadowRoot on DartJsWrapper<JSObject> {
  StyleSheetList get styleSheets => jsObject.styleSheets;
  ObservableArray<CSSStyleSheet> get adoptedStyleSheets =>
      jsObject.adoptedStyleSheets;
  set adoptedStyleSheets(ObservableArray<CSSStyleSheet> value) {
    jsObject.adoptedStyleSheets = value;
  }

  Element? get activeElement => jsObject.activeElement;
}
mixin ParentNode on DartJsWrapper<JSObject> {
  HTMLCollection get children => jsObject.children;
  Element? get firstElementChild => jsObject.firstElementChild;
  Element? get lastElementChild => jsObject.lastElementChild;
  int get childElementCount => jsObject.childElementCount;
}
mixin NonDocumentTypeChildNode on DartJsWrapper<JSObject> {
  Element? get previousElementSibling => jsObject.previousElementSibling;
  Element? get nextElementSibling => jsObject.nextElementSibling;
}
mixin ChildNode on DartJsWrapper<JSObject> {}
mixin Slottable on DartJsWrapper<JSObject> {
  HTMLSlotElement? get assignedSlot => jsObject.assignedSlot;
}

final class NodeList extends DartJsWrapper<js.NodeList> {
  NodeList.fromJsObject(super.jsObject) : super.fromJsObject();

  int get length => jsObject.length;
}

final class HTMLCollection extends DartJsWrapper<js.HTMLCollection> {
  HTMLCollection.fromJsObject(super.jsObject) : super.fromJsObject();

  int get length => jsObject.length;
}

final class MutationObserver extends DartJsWrapper<js.MutationObserver> {
  MutationObserver.fromJsObject(super.jsObject) : super.fromJsObject();
}

final class MutationRecord extends DartJsWrapper<js.MutationRecord> {
  MutationRecord.fromJsObject(super.jsObject) : super.fromJsObject();

  String get type => jsObject.type;

  Node get target => jsObject.target;

  NodeList get addedNodes => jsObject.addedNodes;

  NodeList get removedNodes => jsObject.removedNodes;

  Node? get previousSibling => jsObject.previousSibling;

  Node? get nextSibling => jsObject.nextSibling;

  String? get attributeName => jsObject.attributeName;

  String? get attributeNamespace => jsObject.attributeNamespace;

  String? get oldValue => jsObject.oldValue;
}

class Node<T extends js.Node> extends EventTarget<T> {
  @protected
  Node.fromJsObject(super.jsObject) : super.fromJsObject();

  int get nodeType => jsObject.nodeType;

  String get nodeName => jsObject.nodeName;

  String get baseURI => jsObject.baseURI;

  bool get isConnected => jsObject.isConnected;

  Document? get ownerDocument => jsObject.ownerDocument;

  Node? get parentNode => jsObject.parentNode;

  Element? get parentElement => jsObject.parentElement;

  NodeList get childNodes => jsObject.childNodes;

  Node? get firstChild => jsObject.firstChild;

  Node? get lastChild => jsObject.lastChild;

  Node? get previousSibling => jsObject.previousSibling;

  Node? get nextSibling => jsObject.nextSibling;

  String? get nodeValue => jsObject.nodeValue;

  set nodeValue(String? value) {
    jsObject.nodeValue = value;
  }

  String? get textContent => jsObject.textContent;

  set textContent(String? value) {
    jsObject.textContent = value;
  }
}

JsWrapper<T> safeNodeFromJsObject<T extends js.Node>(T jsObject) =>
    safeJsWrapperFromObject<T>(jsObject, nodeFromJsObject);
JsWrapper<T>? safeNodeFromJsObjectNullable<T extends js.Node>(T? jsObject) =>
    safeJsWrapperFromObjectNullable<T>(jsObject, nodeFromJsObject);

class Document<T extends js.Document> extends Node<T> {
  @protected
  Document.fromJsObject(super.jsObject) : super.fromJsObject();

  DOMImplementation get implementation => jsObject.implementation;

  String get URL => jsObject.URL;

  String get documentURI => jsObject.documentURI;

  String get compatMode => jsObject.compatMode;

  String get characterSet => jsObject.characterSet;

  String get charset => jsObject.charset;

  String get inputEncoding => jsObject.inputEncoding;

  String get contentType => jsObject.contentType;

  DocumentType? get doctype => jsObject.doctype;

  Element? get documentElement => jsObject.documentElement;

  Location? get location => jsObject.location;

  String get domain => jsObject.domain;

  set domain(String value) {
    jsObject.domain = value;
  }

  String get referrer => jsObject.referrer;

  String get cookie => jsObject.cookie;

  set cookie(String value) {
    jsObject.cookie = value;
  }

  String get lastModified => jsObject.lastModified;

  DocumentReadyState get readyState => jsObject.readyState;

  String get title => jsObject.title;

  set title(String value) {
    jsObject.title = value;
  }

  String get dir => jsObject.dir;

  set dir(String value) {
    jsObject.dir = value;
  }

  HTMLElement? get body => jsObject.body;

  set body(HTMLElement? value) {
    jsObject.body = value;
  }

  HTMLHeadElement? get head => jsObject.head;

  HTMLCollection get images => jsObject.images;

  HTMLCollection get embeds => jsObject.embeds;

  HTMLCollection get plugins => jsObject.plugins;

  HTMLCollection get links => jsObject.links;

  HTMLCollection get forms => jsObject.forms;

  HTMLCollection get scripts => jsObject.scripts;

  HTMLOrSVGScriptElement? get currentScript => jsObject.currentScript;

  WindowProxy? get defaultView => jsObject.defaultView;

  String get designMode => jsObject.designMode;

  set designMode(String value) {
    jsObject.designMode = value;
  }

  bool get hidden => jsObject.hidden;

  DocumentVisibilityState get visibilityState => jsObject.visibilityState;

  EventHandler get onreadystatechange => jsObject.onreadystatechange;

  set onreadystatechange(EventHandler value) {
    jsObject.onreadystatechange = value;
  }

  EventHandler get onvisibilitychange => jsObject.onvisibilitychange;

  set onvisibilitychange(EventHandler value) {
    jsObject.onvisibilitychange = value;
  }

  String get fgColor => jsObject.fgColor;

  set fgColor(String value) {
    jsObject.fgColor = value;
  }

  String get linkColor => jsObject.linkColor;

  set linkColor(String value) {
    jsObject.linkColor = value;
  }

  String get vlinkColor => jsObject.vlinkColor;

  set vlinkColor(String value) {
    jsObject.vlinkColor = value;
  }

  String get alinkColor => jsObject.alinkColor;

  set alinkColor(String value) {
    jsObject.alinkColor = value;
  }

  String get bgColor => jsObject.bgColor;

  set bgColor(String value) {
    jsObject.bgColor = value;
  }

  HTMLCollection get anchors => jsObject.anchors;

  HTMLCollection get applets => jsObject.applets;

  HTMLAllCollection get all => jsObject.all;
}

final class XMLDocument extends Document<js.XMLDocument> {
  XMLDocument.fromJsObject(super.jsObject) : super.fromJsObject();
}

final class DOMImplementation extends DartJsWrapper<js.DOMImplementation> {
  DOMImplementation.fromJsObject(super.jsObject) : super.fromJsObject();
}

final class DocumentType extends Node<js.DocumentType> {
  DocumentType.fromJsObject(super.jsObject) : super.fromJsObject();

  String get name => jsObject.name;

  String get publicId => jsObject.publicId;

  String get systemId => jsObject.systemId;
}

class DocumentFragment<T extends js.DocumentFragment> extends Node<T> {
  @protected
  DocumentFragment.fromJsObject(super.jsObject) : super.fromJsObject();
}

final class ShadowRoot extends DocumentFragment<js.ShadowRoot> {
  ShadowRoot.fromJsObject(super.jsObject) : super.fromJsObject();

  ShadowRootMode get mode => jsObject.mode;

  bool get delegatesFocus => jsObject.delegatesFocus;

  SlotAssignmentMode get slotAssignment => jsObject.slotAssignment;

  bool get clonable => jsObject.clonable;

  bool get serializable => jsObject.serializable;

  Element get host => jsObject.host;

  EventHandler get onslotchange => jsObject.onslotchange;

  set onslotchange(EventHandler value) {
    jsObject.onslotchange = value;
  }

  Object? get innerHTML => jsObject.innerHTML;

  set innerHTML(Object? value) {
    jsObject.innerHTML = value;
  }
}

class Element<T extends js.Element> extends Node<T> {
  @protected
  Element.fromJsObject(super.jsObject) : super.fromJsObject();

  String? get namespaceURI => jsObject.namespaceURI;

  String? get prefix => jsObject.prefix;

  String get localName => jsObject.localName;

  String get tagName => jsObject.tagName;

  String get id => jsObject.id;

  set id(String value) {
    jsObject.id = value;
  }

  String get className => jsObject.className;

  set className(String value) {
    jsObject.className = value;
  }

  DOMTokenList get classList => jsObject.classList;

  String get slot => jsObject.slot;

  set slot(String value) {
    jsObject.slot = value;
  }

  NamedNodeMap get attributes => jsObject.attributes;

  ShadowRoot? get shadowRoot => jsObject.shadowRoot;

  Object? get innerHTML => jsObject.innerHTML;

  set innerHTML(Object? value) {
    jsObject.innerHTML = value;
  }

  Object? get outerHTML => jsObject.outerHTML;

  set outerHTML(Object? value) {
    jsObject.outerHTML = value;
  }
}

JsWrapper<T> safeElementFromJsObject<T extends js.Element>(T jsObject) =>
    safeJsWrapperFromObject<T>(jsObject, elementFromJsObject);
JsWrapper<T>? safeElementFromJsObjectNullable<T extends js.Element>(
  T? jsObject,
) => safeJsWrapperFromObjectNullable<T>(jsObject, elementFromJsObject);

final class NamedNodeMap extends DartJsWrapper<js.NamedNodeMap> {
  NamedNodeMap.fromJsObject(super.jsObject) : super.fromJsObject();

  int get length => jsObject.length;
}

final class Attr extends Node<js.Attr> {
  Attr.fromJsObject(super.jsObject) : super.fromJsObject();

  String? get namespaceURI => jsObject.namespaceURI;

  String? get prefix => jsObject.prefix;

  String get localName => jsObject.localName;

  String get name => jsObject.name;

  String get value => jsObject.value;

  set value(String value) {
    jsObject.value = value;
  }

  Element? get ownerElement => jsObject.ownerElement;

  bool get specified => jsObject.specified;
}

class CharacterData<T extends js.CharacterData> extends Node<T> {
  @protected
  CharacterData.fromJsObject(super.jsObject) : super.fromJsObject();

  String get data => jsObject.data;

  set data(String value) {
    jsObject.data = value;
  }

  int get length => jsObject.length;
}

class Text<T extends js.Text> extends CharacterData<T> {
  @protected
  Text.fromJsObject(super.jsObject) : super.fromJsObject();

  String get wholeText => jsObject.wholeText;
}

final class CDATASection extends Text<js.CDATASection> {
  CDATASection.fromJsObject(super.jsObject) : super.fromJsObject();
}

final class ProcessingInstruction
    extends CharacterData<js.ProcessingInstruction> {
  ProcessingInstruction.fromJsObject(super.jsObject) : super.fromJsObject();

  String get target => jsObject.target;
}

final class Comment extends CharacterData<js.Comment> {
  Comment.fromJsObject(super.jsObject) : super.fromJsObject();
}

class AbstractRange<T extends js.AbstractRange> extends DartJsWrapper<T> {
  @protected
  AbstractRange.fromJsObject(super.jsObject) : super.fromJsObject();

  Node get startContainer => jsObject.startContainer;

  int get startOffset => jsObject.startOffset;

  Node get endContainer => jsObject.endContainer;

  int get endOffset => jsObject.endOffset;

  bool get collapsed => jsObject.collapsed;
}

final class StaticRange extends AbstractRange<js.StaticRange> {
  StaticRange.fromJsObject(super.jsObject) : super.fromJsObject();
}

final class Range extends AbstractRange<js.Range> {
  Range.fromJsObject(super.jsObject) : super.fromJsObject();

  Node get commonAncestorContainer => jsObject.commonAncestorContainer;

  String get stringifier => jsObject.stringifier;

  set stringifier(String value) {
    jsObject.stringifier = value;
  }
}

final class NodeIterator extends DartJsWrapper<js.NodeIterator> {
  NodeIterator.fromJsObject(super.jsObject) : super.fromJsObject();

  Node get root => jsObject.root;

  Node get referenceNode => jsObject.referenceNode;

  bool get pointerBeforeReferenceNode => jsObject.pointerBeforeReferenceNode;

  int get whatToShow => jsObject.whatToShow;

  NodeFilter? get filter => jsObject.filter;
}

final class TreeWalker extends DartJsWrapper<js.TreeWalker> {
  TreeWalker.fromJsObject(super.jsObject) : super.fromJsObject();

  Node get root => jsObject.root;

  int get whatToShow => jsObject.whatToShow;

  NodeFilter? get filter => jsObject.filter;

  Node get currentNode => jsObject.currentNode;

  set currentNode(Node value) {
    jsObject.currentNode = value;
  }
}

final class NodeFilter extends DartJsWrapper<js.NodeFilter> {
  NodeFilter.fromJsObject(super.jsObject) : super.fromJsObject();
}

final class DOMTokenList extends DartJsWrapper<js.DOMTokenList> {
  DOMTokenList.fromJsObject(super.jsObject) : super.fromJsObject();

  int get length => jsObject.length;

  String get value => jsObject.value;

  set value(String value) {
    jsObject.value = value;
  }
}

final class XPathResult extends DartJsWrapper<js.XPathResult> {
  XPathResult.fromJsObject(super.jsObject) : super.fromJsObject();

  int get resultType => jsObject.resultType;

  double get numberValue => jsObject.numberValue;

  String get stringValue => jsObject.stringValue;

  bool get booleanValue => jsObject.booleanValue;

  Node? get singleNodeValue => jsObject.singleNodeValue;

  bool get invalidIteratorState => jsObject.invalidIteratorState;

  int get snapshotLength => jsObject.snapshotLength;
}

final class XPathExpression extends DartJsWrapper<js.XPathExpression> {
  XPathExpression.fromJsObject(super.jsObject) : super.fromJsObject();
}

final class XPathNSResolver extends DartJsWrapper<js.XPathNSResolver> {
  XPathNSResolver.fromJsObject(super.jsObject) : super.fromJsObject();
}

mixin XPathEvaluatorBase on DartJsWrapper<JSObject> {}

final class XPathEvaluator extends DartJsWrapper<js.XPathEvaluator> {
  XPathEvaluator.fromJsObject(super.jsObject) : super.fromJsObject();
}

final class XSLTProcessor extends DartJsWrapper<js.XSLTProcessor> {
  XSLTProcessor.fromJsObject(super.jsObject) : super.fromJsObject();
}
