// Generated by Rampage on 2025-02-07 07:51:14.040998

import 'package:meta/meta.dart';
import 'package:rampage_js_interop/js_interop.dart' as js;

import 'wrapper.dart';

class DOMPointReadOnly<T extends js.DOMPointReadOnly> extends DartJsWrapper<T> {
  @protected
  DOMPointReadOnly.fromJsObject(super.jsObject) : super.fromJsObject();

  double get x => jsObject.x;

  double get y => jsObject.y;

  double get z => jsObject.z;

  double get w => jsObject.w;
}

final class DOMPoint extends DOMPointReadOnly<js.DOMPoint> {
  DOMPoint.fromJsObject(super.jsObject) : super.fromJsObject();

  double get x => jsObject.x;

  set x(double value) {
    jsObject.x = value;
  }

  double get y => jsObject.y;

  set y(double value) {
    jsObject.y = value;
  }

  double get z => jsObject.z;

  set z(double value) {
    jsObject.z = value;
  }

  double get w => jsObject.w;

  set w(double value) {
    jsObject.w = value;
  }
}

class DOMRectReadOnly<T extends js.DOMRectReadOnly> extends DartJsWrapper<T> {
  @protected
  DOMRectReadOnly.fromJsObject(super.jsObject) : super.fromJsObject();

  double get x => jsObject.x;

  double get y => jsObject.y;

  double get width => jsObject.width;

  double get height => jsObject.height;

  double get top => jsObject.top;

  double get right => jsObject.right;

  double get bottom => jsObject.bottom;

  double get left => jsObject.left;
}

final class DOMRect extends DOMRectReadOnly<js.DOMRect> {
  DOMRect.fromJsObject(super.jsObject) : super.fromJsObject();

  double get x => jsObject.x;

  set x(double value) {
    jsObject.x = value;
  }

  double get y => jsObject.y;

  set y(double value) {
    jsObject.y = value;
  }

  double get width => jsObject.width;

  set width(double value) {
    jsObject.width = value;
  }

  double get height => jsObject.height;

  set height(double value) {
    jsObject.height = value;
  }
}

final class DOMRectList extends DartJsWrapper<js.DOMRectList> {
  DOMRectList.fromJsObject(super.jsObject) : super.fromJsObject();

  int get length => jsObject.length;
}

final class DOMQuad extends DartJsWrapper<js.DOMQuad> {
  DOMQuad.fromJsObject(super.jsObject) : super.fromJsObject();

  DOMPoint get p1 => jsObject.p1;

  DOMPoint get p2 => jsObject.p2;

  DOMPoint get p3 => jsObject.p3;

  DOMPoint get p4 => jsObject.p4;
}

class DOMMatrixReadOnly<T extends js.DOMMatrixReadOnly>
    extends DartJsWrapper<T> {
  @protected
  DOMMatrixReadOnly.fromJsObject(super.jsObject) : super.fromJsObject();

  double get a => jsObject.a;

  double get b => jsObject.b;

  double get c => jsObject.c;

  double get d => jsObject.d;

  double get e => jsObject.e;

  double get f => jsObject.f;

  double get m11 => jsObject.m11;

  double get m12 => jsObject.m12;

  double get m13 => jsObject.m13;

  double get m14 => jsObject.m14;

  double get m21 => jsObject.m21;

  double get m22 => jsObject.m22;

  double get m23 => jsObject.m23;

  double get m24 => jsObject.m24;

  double get m31 => jsObject.m31;

  double get m32 => jsObject.m32;

  double get m33 => jsObject.m33;

  double get m34 => jsObject.m34;

  double get m41 => jsObject.m41;

  double get m42 => jsObject.m42;

  double get m43 => jsObject.m43;

  double get m44 => jsObject.m44;

  bool get is2D => jsObject.is2D;

  bool get isIdentity => jsObject.isIdentity;

  String get stringifier => jsObject.stringifier;

  set stringifier(String value) {
    jsObject.stringifier = value;
  }
}

final class DOMMatrix extends DOMMatrixReadOnly<js.DOMMatrix> {
  DOMMatrix.fromJsObject(super.jsObject) : super.fromJsObject();

  double get a => jsObject.a;

  set a(double value) {
    jsObject.a = value;
  }

  double get b => jsObject.b;

  set b(double value) {
    jsObject.b = value;
  }

  double get c => jsObject.c;

  set c(double value) {
    jsObject.c = value;
  }

  double get d => jsObject.d;

  set d(double value) {
    jsObject.d = value;
  }

  double get e => jsObject.e;

  set e(double value) {
    jsObject.e = value;
  }

  double get f => jsObject.f;

  set f(double value) {
    jsObject.f = value;
  }

  double get m11 => jsObject.m11;

  set m11(double value) {
    jsObject.m11 = value;
  }

  double get m12 => jsObject.m12;

  set m12(double value) {
    jsObject.m12 = value;
  }

  double get m13 => jsObject.m13;

  set m13(double value) {
    jsObject.m13 = value;
  }

  double get m14 => jsObject.m14;

  set m14(double value) {
    jsObject.m14 = value;
  }

  double get m21 => jsObject.m21;

  set m21(double value) {
    jsObject.m21 = value;
  }

  double get m22 => jsObject.m22;

  set m22(double value) {
    jsObject.m22 = value;
  }

  double get m23 => jsObject.m23;

  set m23(double value) {
    jsObject.m23 = value;
  }

  double get m24 => jsObject.m24;

  set m24(double value) {
    jsObject.m24 = value;
  }

  double get m31 => jsObject.m31;

  set m31(double value) {
    jsObject.m31 = value;
  }

  double get m32 => jsObject.m32;

  set m32(double value) {
    jsObject.m32 = value;
  }

  double get m33 => jsObject.m33;

  set m33(double value) {
    jsObject.m33 = value;
  }

  double get m34 => jsObject.m34;

  set m34(double value) {
    jsObject.m34 = value;
  }

  double get m41 => jsObject.m41;

  set m41(double value) {
    jsObject.m41 = value;
  }

  double get m42 => jsObject.m42;

  set m42(double value) {
    jsObject.m42 = value;
  }

  double get m43 => jsObject.m43;

  set m43(double value) {
    jsObject.m43 = value;
  }

  double get m44 => jsObject.m44;

  set m44(double value) {
    jsObject.m44 = value;
  }
}
