// Generated by Rampage on 2025-02-07 07:51:14.067581

import 'package:rampage_js_interop/js_interop.dart' as js;

import 'dom.dart';

final class Performance extends EventTarget<js.Performance> {
  Performance.fromJsObject(super.jsObject) : super.fromJsObject();

  DOMHighResTimeStamp get timeOrigin => jsObject.timeOrigin;
}
