// Generated by Rampage on 2025-02-07 07:51:14.313665

import 'package:rampage_js_interop/js_interop.dart' as js;

import 'dom.dart';
import 'geometry.dart';
import 'wrapper.dart';

enum ResizeObserverBoxOptions {
  borderBox('border-box'),
  contentBox('content-box'),
  devicePixelContentBox('device-pixel-content-box');

  const ResizeObserverBoxOptions(this.toJS);

  final String toJS;
}

extension ResizeObserverBoxOptionsDartObject on String {
  ResizeObserverBoxOptions get toDart => switch (this) {
    'border-box' => ResizeObserverBoxOptions.borderBox,
    'content-box' => ResizeObserverBoxOptions.contentBox,
    'device-pixel-content-box' =>
      ResizeObserverBoxOptions.devicePixelContentBox,
    _ =>
      throw UnsupportedError(
        '$this is not a member of ResizeObserverBoxOptions',
      ),
  };
}

final class ResizeObserver extends DartJsWrapper<js.ResizeObserver> {
  ResizeObserver.fromJsObject(super.jsObject) : super.fromJsObject();
}

final class ResizeObserverEntry extends DartJsWrapper<js.ResizeObserverEntry> {
  ResizeObserverEntry.fromJsObject(super.jsObject) : super.fromJsObject();

  Element get target => jsObject.target;

  DOMRectReadOnly get contentRect => jsObject.contentRect;

  FrozenArray<ResizeObserverSize> get borderBoxSize => jsObject.borderBoxSize;

  FrozenArray<ResizeObserverSize> get contentBoxSize => jsObject.contentBoxSize;

  FrozenArray<ResizeObserverSize> get devicePixelContentBoxSize =>
      jsObject.devicePixelContentBoxSize;
}

final class ResizeObserverSize extends DartJsWrapper<js.ResizeObserverSize> {
  ResizeObserverSize.fromJsObject(super.jsObject) : super.fromJsObject();

  double get inlineSize => jsObject.inlineSize;

  double get blockSize => jsObject.blockSize;
}
