// Generated by Rampage on 2025-02-07 07:51:14.335999

import 'package:meta/meta.dart';
import 'package:rampage_js_interop/js_interop.dart' as js;

import 'dom.dart';
import 'html.dart';

class UIEvent<T extends js.UIEvent> extends Event<T> {
  @protected
  UIEvent.fromJsObject(super.jsObject) : super.fromJsObject();

  Window? get view => jsObject.view;

  int get detail => jsObject.detail;

  int get which => jsObject.which;
}

final class FocusEvent extends UIEvent<js.FocusEvent> {
  FocusEvent.fromJsObject(super.jsObject) : super.fromJsObject();

  EventTarget? get relatedTarget => jsObject.relatedTarget;
}

class MouseEvent<T extends js.MouseEvent> extends UIEvent<T> {
  @protected
  MouseEvent.fromJsObject(super.jsObject) : super.fromJsObject();

  int get screenX => jsObject.screenX;

  int get screenY => jsObject.screenY;

  int get clientX => jsObject.clientX;

  int get clientY => jsObject.clientY;

  int get layerX => jsObject.layerX;

  int get layerY => jsObject.layerY;

  bool get ctrlKey => jsObject.ctrlKey;

  bool get shiftKey => jsObject.shiftKey;

  bool get altKey => jsObject.altKey;

  bool get metaKey => jsObject.metaKey;

  int get button => jsObject.button;

  int get buttons => jsObject.buttons;

  EventTarget? get relatedTarget => jsObject.relatedTarget;
}

final class WheelEvent extends MouseEvent<js.WheelEvent> {
  WheelEvent.fromJsObject(super.jsObject) : super.fromJsObject();

  double get deltaX => jsObject.deltaX;

  double get deltaY => jsObject.deltaY;

  double get deltaZ => jsObject.deltaZ;

  int get deltaMode => jsObject.deltaMode;
}

final class InputEvent extends UIEvent<js.InputEvent> {
  InputEvent.fromJsObject(super.jsObject) : super.fromJsObject();

  String? get data => jsObject.data;

  bool get isComposing => jsObject.isComposing;

  String get inputType => jsObject.inputType;
}

final class KeyboardEvent extends UIEvent<js.KeyboardEvent> {
  KeyboardEvent.fromJsObject(super.jsObject) : super.fromJsObject();

  String get key => jsObject.key;

  String get code => jsObject.code;

  int get location => jsObject.location;

  bool get ctrlKey => jsObject.ctrlKey;

  bool get shiftKey => jsObject.shiftKey;

  bool get altKey => jsObject.altKey;

  bool get metaKey => jsObject.metaKey;

  bool get repeat => jsObject.repeat;

  bool get isComposing => jsObject.isComposing;

  int get charCode => jsObject.charCode;

  int get keyCode => jsObject.keyCode;
}

final class CompositionEvent extends UIEvent<js.CompositionEvent> {
  CompositionEvent.fromJsObject(super.jsObject) : super.fromJsObject();

  String get data => jsObject.data;
}

final class TextEvent extends UIEvent<js.TextEvent> {
  TextEvent.fromJsObject(super.jsObject) : super.fromJsObject();

  String get data => jsObject.data;
}
