// Generated by Rampage on 2025-02-07 07:51:14.349494

import 'package:meta/meta.dart';
import 'package:rampage_js_interop/js_interop.dart' as js;

import 'dom.dart';
import 'html.dart';
import 'wrapper.dart';

enum XMLHttpRequestResponseType {
  empty(''),
  arraybuffer('arraybuffer'),
  blob('blob'),
  document('document'),
  json('json'),
  text('text');

  const XMLHttpRequestResponseType(this.toJS);

  final String toJS;
}

extension XMLHttpRequestResponseTypeDartObject on String {
  XMLHttpRequestResponseType get toDart => switch (this) {
    '' => XMLHttpRequestResponseType.empty,
    'arraybuffer' => XMLHttpRequestResponseType.arraybuffer,
    'blob' => XMLHttpRequestResponseType.blob,
    'document' => XMLHttpRequestResponseType.document,
    'json' => XMLHttpRequestResponseType.json,
    'text' => XMLHttpRequestResponseType.text,
    _ =>
      throw UnsupportedError(
        '$this is not a member of XMLHttpRequestResponseType',
      ),
  };
}

class XMLHttpRequestEventTarget<T extends js.XMLHttpRequestEventTarget>
    extends EventTarget<T> {
  @protected
  XMLHttpRequestEventTarget.fromJsObject(super.jsObject) : super.fromJsObject();

  EventHandler get onloadstart => jsObject.onloadstart;

  set onloadstart(EventHandler value) {
    jsObject.onloadstart = value;
  }

  EventHandler get onprogress => jsObject.onprogress;

  set onprogress(EventHandler value) {
    jsObject.onprogress = value;
  }

  EventHandler get onabort => jsObject.onabort;

  set onabort(EventHandler value) {
    jsObject.onabort = value;
  }

  EventHandler get onerror => jsObject.onerror;

  set onerror(EventHandler value) {
    jsObject.onerror = value;
  }

  EventHandler get onload => jsObject.onload;

  set onload(EventHandler value) {
    jsObject.onload = value;
  }

  EventHandler get ontimeout => jsObject.ontimeout;

  set ontimeout(EventHandler value) {
    jsObject.ontimeout = value;
  }

  EventHandler get onloadend => jsObject.onloadend;

  set onloadend(EventHandler value) {
    jsObject.onloadend = value;
  }
}

final class XMLHttpRequestUpload
    extends XMLHttpRequestEventTarget<js.XMLHttpRequestUpload> {
  XMLHttpRequestUpload.fromJsObject(super.jsObject) : super.fromJsObject();
}

final class XMLHttpRequest
    extends XMLHttpRequestEventTarget<js.XMLHttpRequest> {
  XMLHttpRequest.fromJsObject(super.jsObject) : super.fromJsObject();

  EventHandler get onreadystatechange => jsObject.onreadystatechange;

  set onreadystatechange(EventHandler value) {
    jsObject.onreadystatechange = value;
  }

  int get readyState => jsObject.readyState;

  int get timeout => jsObject.timeout;

  set timeout(int value) {
    jsObject.timeout = value;
  }

  bool get withCredentials => jsObject.withCredentials;

  set withCredentials(bool value) {
    jsObject.withCredentials = value;
  }

  XMLHttpRequestUpload get upload => jsObject.upload;

  String get responseURL => jsObject.responseURL;

  int get status => jsObject.status;

  String get statusText => jsObject.statusText;

  XMLHttpRequestResponseType get responseType => jsObject.responseType;

  set responseType(XMLHttpRequestResponseType value) {
    jsObject.responseType = value;
  }

  Object get response => jsObject.response;

  String get responseText => jsObject.responseText;

  Document? get responseXML => jsObject.responseXML;
}

final class FormData extends DartJsWrapper<js.FormData> {
  FormData.fromJsObject(super.jsObject) : super.fromJsObject();
}

final class ProgressEvent extends Event<js.ProgressEvent> {
  ProgressEvent.fromJsObject(super.jsObject) : super.fromJsObject();

  bool get lengthComputable => jsObject.lengthComputable;

  int get loaded => jsObject.loaded;

  int get total => jsObject.total;
}
