// Generated by Rampage on 2025-02-07 08:13:59.729784

import 'dart:js_interop';

typedef ViewTransitionUpdateCallback = JSFunction;
extension type ViewTransition._(JSObject _) implements JSObject {
  external JSPromise<JSAny?> get updateCallbackDone;
  external JSPromise<JSAny?> get ready;
  external JSPromise<JSAny?> get finished;
  external void skipTransition();
}
