// Generated by Rampage on 2025-02-07 08:13:59.646533

import 'dart:js_interop';

import 'geometry.dart';

extension type CSSNumericType._(JSObject _) implements JSObject {
  external factory CSSNumericType({
    int length,
    int angle,
    int time,
    int frequency,
    int resolution,
    int flex,
    int percent,
    CSSNumericBaseType percentHint,
  });

  external int get length;
  external set length(int value);
  external int get angle;
  external set angle(int value);
  external int get time;
  external set time(int value);
  external int get frequency;
  external set frequency(int value);
  external int get resolution;
  external set resolution(int value);
  external int get flex;
  external set flex(int value);
  external int get percent;
  external set percent(int value);
  external CSSNumericBaseType get percentHint;
  external set percentHint(CSSNumericBaseType value);
}
extension type CSSMatrixComponentOptions._(JSObject _) implements JSObject {
  external factory CSSMatrixComponentOptions({bool is2D});

  external bool get is2D;
  external set is2D(bool value);
}
typedef CSSNumericBaseType = String;
typedef CSSMathOperator = String;
extension type CSSStyleValue._(JSObject _) implements JSObject {
  external static CSSStyleValue parse(String property, String cssText);
  external static JSArray<CSSStyleValue> parseAll(
    String property,
    String cssText,
  );
}
extension type StylePropertyMapReadOnly._(JSObject _) implements JSObject {
  external int get size;
  external JSAny get(String property);
  external JSArray<CSSStyleValue> getAll(String property);
  external bool has(String property);
}
extension type StylePropertyMap._(JSObject _)
    implements JSObject, StylePropertyMapReadOnly {
  external void set(String property, JSAny values);
  external void append(String property, JSAny values);
  external void delete(String property);
  external void clear();
}
extension type CSSUnparsedValue._(JSObject _)
    implements JSObject, CSSStyleValue {
  external factory CSSUnparsedValue(JSArray<CSSUnparsedSegment> members);

  external int get length;
}
extension type CSSVariableReferenceValue._(JSObject _) implements JSObject {
  external factory CSSVariableReferenceValue(
    String variable, [
    CSSUnparsedValue? fallback,
  ]);

  external String get variable;
  external set variable(String value);
  external CSSUnparsedValue? get fallback;
}
extension type CSSKeywordValue._(JSObject _)
    implements JSObject, CSSStyleValue {
  external factory CSSKeywordValue(String value);

  external String get value;
  external set value(String value);
}
extension type CSSNumericValue._(JSObject _)
    implements JSObject, CSSStyleValue {
  external CSSNumericValue add(CSSNumberish values);
  external CSSNumericValue sub(CSSNumberish values);
  external CSSNumericValue mul(CSSNumberish values);
  external CSSNumericValue div(CSSNumberish values);
  external CSSNumericValue min(CSSNumberish values);
  external CSSNumericValue max(CSSNumberish values);
  external bool equals(CSSNumberish value);
  external CSSUnitValue to(String unit);
  external CSSMathSum toSum(String units);
  external CSSNumericType type();
  external static CSSNumericValue parse(String cssText);
}
extension type CSSUnitValue._(JSObject _) implements JSObject, CSSNumericValue {
  external factory CSSUnitValue(double value, String unit);

  external double get value;
  external set value(double value);
  external String get unit;
}
extension type CSSMathValue._(JSObject _) implements JSObject, CSSNumericValue {
  external CSSMathOperator get operator;
}
extension type CSSMathSum._(JSObject _) implements JSObject, CSSMathValue {
  external factory CSSMathSum(CSSNumberish args);

  external CSSNumericArray get values;
}
extension type CSSMathProduct._(JSObject _) implements JSObject, CSSMathValue {
  external factory CSSMathProduct(CSSNumberish args);

  external CSSNumericArray get values;
}
extension type CSSMathNegate._(JSObject _) implements JSObject, CSSMathValue {
  external factory CSSMathNegate(CSSNumberish arg);

  external CSSNumericValue get value;
}
extension type CSSMathInvert._(JSObject _) implements JSObject, CSSMathValue {
  external factory CSSMathInvert(CSSNumberish arg);

  external CSSNumericValue get value;
}
extension type CSSMathMin._(JSObject _) implements JSObject, CSSMathValue {
  external factory CSSMathMin(CSSNumberish args);

  external CSSNumericArray get values;
}
extension type CSSMathMax._(JSObject _) implements JSObject, CSSMathValue {
  external factory CSSMathMax(CSSNumberish args);

  external CSSNumericArray get values;
}
extension type CSSMathClamp._(JSObject _) implements JSObject, CSSMathValue {
  external factory CSSMathClamp(
    CSSNumberish lower,
    CSSNumberish value,
    CSSNumberish upper,
  );

  external CSSNumericValue get lower;
  external CSSNumericValue get value;
  external CSSNumericValue get upper;
}
extension type CSSNumericArray._(JSObject _) implements JSObject {
  external int get length;
}
extension type CSSTransformValue._(JSObject _)
    implements JSObject, CSSStyleValue {
  external factory CSSTransformValue(JSArray<CSSTransformComponent> transforms);

  external int get length;
  external bool get is2D;
  external DOMMatrix toMatrix();
}
extension type CSSTransformComponent._(JSObject _) implements JSObject {
  external bool get is2D;
  external set is2D(bool value);
  external DOMMatrix toMatrix();
}
extension type CSSTranslate._(JSObject _)
    implements JSObject, CSSTransformComponent {
  external factory CSSTranslate(
    CSSNumericValue x,
    CSSNumericValue y, [
    CSSNumericValue z,
  ]);

  external CSSNumericValue get x;
  external set x(CSSNumericValue value);
  external CSSNumericValue get y;
  external set y(CSSNumericValue value);
  external CSSNumericValue get z;
  external set z(CSSNumericValue value);
}
extension type CSSRotate._(JSObject _)
    implements JSObject, CSSTransformComponent {
  external factory CSSRotate(CSSNumericValue angle);

  external factory CSSRotate(
    CSSNumberish x,
    CSSNumberish y,
    CSSNumberish z,
    CSSNumericValue angle,
  );

  external CSSNumberish get x;
  external set x(CSSNumberish value);
  external CSSNumberish get y;
  external set y(CSSNumberish value);
  external CSSNumberish get z;
  external set z(CSSNumberish value);
  external CSSNumericValue get angle;
  external set angle(CSSNumericValue value);
}
extension type CSSScale._(JSObject _)
    implements JSObject, CSSTransformComponent {
  external factory CSSScale(CSSNumberish x, CSSNumberish y, [CSSNumberish z]);

  external CSSNumberish get x;
  external set x(CSSNumberish value);
  external CSSNumberish get y;
  external set y(CSSNumberish value);
  external CSSNumberish get z;
  external set z(CSSNumberish value);
}
extension type CSSSkew._(JSObject _)
    implements JSObject, CSSTransformComponent {
  external factory CSSSkew(CSSNumericValue ax, CSSNumericValue ay);

  external CSSNumericValue get ax;
  external set ax(CSSNumericValue value);
  external CSSNumericValue get ay;
  external set ay(CSSNumericValue value);
}
extension type CSSSkewX._(JSObject _)
    implements JSObject, CSSTransformComponent {
  external factory CSSSkewX(CSSNumericValue ax);

  external CSSNumericValue get ax;
  external set ax(CSSNumericValue value);
}
extension type CSSSkewY._(JSObject _)
    implements JSObject, CSSTransformComponent {
  external factory CSSSkewY(CSSNumericValue ay);

  external CSSNumericValue get ay;
  external set ay(CSSNumericValue value);
}
extension type CSSPerspective._(JSObject _)
    implements JSObject, CSSTransformComponent {
  external factory CSSPerspective(CSSPerspectiveValue length);

  external CSSPerspectiveValue get length;
  external set length(CSSPerspectiveValue value);
}
extension type CSSMatrixComponent._(JSObject _)
    implements JSObject, CSSTransformComponent {
  external factory CSSMatrixComponent(
    DOMMatrixReadOnly matrix, [
    CSSMatrixComponentOptions options,
  ]);

  external DOMMatrix get matrix;
  external set matrix(DOMMatrix value);
}
extension type CSSImageValue._(JSObject _) implements JSObject, CSSStyleValue {}
extension type CSSColorValue._(JSObject _) implements JSObject, CSSStyleValue {
  external static JSAny parse(String cssText);
}
extension type CSSRGB._(JSObject _) implements JSObject, CSSColorValue {
  external factory CSSRGB(
    CSSColorRGBComp r,
    CSSColorRGBComp g,
    CSSColorRGBComp b, [
    CSSColorPercent alpha,
  ]);

  external CSSColorRGBComp get r;
  external set r(CSSColorRGBComp value);
  external CSSColorRGBComp get g;
  external set g(CSSColorRGBComp value);
  external CSSColorRGBComp get b;
  external set b(CSSColorRGBComp value);
  external CSSColorPercent get alpha;
  external set alpha(CSSColorPercent value);
}
extension type CSSHSL._(JSObject _) implements JSObject, CSSColorValue {
  external factory CSSHSL(
    CSSColorAngle h,
    CSSColorPercent s,
    CSSColorPercent l, [
    CSSColorPercent alpha,
  ]);

  external CSSColorAngle get h;
  external set h(CSSColorAngle value);
  external CSSColorPercent get s;
  external set s(CSSColorPercent value);
  external CSSColorPercent get l;
  external set l(CSSColorPercent value);
  external CSSColorPercent get alpha;
  external set alpha(CSSColorPercent value);
}
extension type CSSHWB._(JSObject _) implements JSObject, CSSColorValue {
  external factory CSSHWB(
    CSSNumericValue h,
    CSSNumberish w,
    CSSNumberish b, [
    CSSNumberish alpha,
  ]);

  external CSSNumericValue get h;
  external set h(CSSNumericValue value);
  external CSSNumberish get w;
  external set w(CSSNumberish value);
  external CSSNumberish get b;
  external set b(CSSNumberish value);
  external CSSNumberish get alpha;
  external set alpha(CSSNumberish value);
}
extension type CSSLab._(JSObject _) implements JSObject, CSSColorValue {
  external factory CSSLab(
    CSSColorPercent l,
    CSSColorNumber a,
    CSSColorNumber b, [
    CSSColorPercent alpha,
  ]);

  external CSSColorPercent get l;
  external set l(CSSColorPercent value);
  external CSSColorNumber get a;
  external set a(CSSColorNumber value);
  external CSSColorNumber get b;
  external set b(CSSColorNumber value);
  external CSSColorPercent get alpha;
  external set alpha(CSSColorPercent value);
}
extension type CSSLCH._(JSObject _) implements JSObject, CSSColorValue {
  external factory CSSLCH(
    CSSColorPercent l,
    CSSColorPercent c,
    CSSColorAngle h, [
    CSSColorPercent alpha,
  ]);

  external CSSColorPercent get l;
  external set l(CSSColorPercent value);
  external CSSColorPercent get c;
  external set c(CSSColorPercent value);
  external CSSColorAngle get h;
  external set h(CSSColorAngle value);
  external CSSColorPercent get alpha;
  external set alpha(CSSColorPercent value);
}
extension type CSSOKLab._(JSObject _) implements JSObject, CSSColorValue {
  external factory CSSOKLab(
    CSSColorPercent l,
    CSSColorNumber a,
    CSSColorNumber b, [
    CSSColorPercent alpha,
  ]);

  external CSSColorPercent get l;
  external set l(CSSColorPercent value);
  external CSSColorNumber get a;
  external set a(CSSColorNumber value);
  external CSSColorNumber get b;
  external set b(CSSColorNumber value);
  external CSSColorPercent get alpha;
  external set alpha(CSSColorPercent value);
}
extension type CSSOKLCH._(JSObject _) implements JSObject, CSSColorValue {
  external factory CSSOKLCH(
    CSSColorPercent l,
    CSSColorPercent c,
    CSSColorAngle h, [
    CSSColorPercent alpha,
  ]);

  external CSSColorPercent get l;
  external set l(CSSColorPercent value);
  external CSSColorPercent get c;
  external set c(CSSColorPercent value);
  external CSSColorAngle get h;
  external set h(CSSColorAngle value);
  external CSSColorPercent get alpha;
  external set alpha(CSSColorPercent value);
}
extension type CSSColor._(JSObject _) implements JSObject, CSSColorValue {
  external factory CSSColor(
    CSSKeywordish colorSpace,
    JSArray<CSSColorPercent> channels, [
    CSSNumberish alpha,
  ]);

  external CSSKeywordish get colorSpace;
  external set colorSpace(CSSKeywordish value);
  external JSArray<CSSColorPercent> get channels;
  external set channels(JSArray<CSSColorPercent> value);
  external CSSNumberish get alpha;
  external set alpha(CSSNumberish value);
}
typedef CSSUnparsedSegment = JSAny;
typedef CSSKeywordish = JSAny;
typedef CSSNumberish = JSAny;
typedef CSSPerspectiveValue = JSAny;
typedef CSSColorRGBComp = JSAny;
typedef CSSColorPercent = JSAny;
typedef CSSColorNumber = JSAny;
typedef CSSColorAngle = JSAny;
