// Generated by Rampage on 2025-02-07 08:13:59.385983

import 'dart:js_interop';

import 'css_typed_om.dart';

extension type CSSStyleSheetInit._(JSObject _) implements JSObject {
  external factory CSSStyleSheetInit({
    String baseURL,
    JSAny media,
    bool disabled,
  });

  external String get baseURL;
  external set baseURL(String value);
  external JSAny get media;
  external set media(JSAny value);
  external bool get disabled;
  external set disabled(bool value);
}
extension type MediaList._(JSObject _) implements JSObject {
  external int get length;
  external void appendMedium(CSSOMString medium);
  external void deleteMedium(CSSOMString medium);
}
extension type StyleSheet._(JSObject _) implements JSObject {
  external CSSOMString get type;
  external String? get href;
  external JSAny get ownerNode;
  external CSSStyleSheet? get parentStyleSheet;
  external String? get title;
  external MediaList get media;
  external bool get disabled;
  external set disabled(bool value);
}
extension type CSSStyleSheet._(JSObject _) implements JSObject, StyleSheet {
  external factory CSSStyleSheet([CSSStyleSheetInit options]);

  external CSSRule? get ownerRule;
  external CSSRuleList get cssRules;
  external CSSRuleList get rules;
  external int insertRule(CSSOMString rule, [int index]);
  external void deleteRule(int index);
  external JSPromise<CSSStyleSheet> replace(String text);
  external void replaceSync(String text);
  external int addRule([String selector, String style, int index]);
  external void removeRule([int index]);
}
extension type StyleSheetList._(JSObject _) implements JSObject {
  external int get length;
}
extension type LinkStyle._(JSObject _) implements JSObject {
  external CSSStyleSheet? get sheet;
}
extension type CSSRuleList._(JSObject _) implements JSObject {
  external int get length;
}
extension type CSSRule._(JSObject _) implements JSObject {
  external CSSOMString get cssText;
  external set cssText(CSSOMString value);
  external CSSRule? get parentRule;
  external CSSStyleSheet? get parentStyleSheet;
  external int get type;
}
extension type CSSStyleRule._(JSObject _) implements JSObject, CSSRule {
  external CSSOMString get selectorText;
  external set selectorText(CSSOMString value);
  external CSSStyleDeclaration get style;
  external StylePropertyMap get styleMap;
}
extension type CSSImportRule._(JSObject _) implements JSObject, CSSRule {
  external String get href;
  external MediaList get media;
  external CSSStyleSheet get styleSheet;
}
extension type CSSGroupingRule._(JSObject _) implements JSObject, CSSRule {
  external CSSRuleList get cssRules;
  external int insertRule(CSSOMString rule, [int index]);
  external void deleteRule(int index);
}
extension type CSSPageRule._(JSObject _) implements JSObject, CSSGroupingRule {
  external CSSOMString get selectorText;
  external set selectorText(CSSOMString value);
  external CSSStyleDeclaration get style;
}
extension type CSSMarginRule._(JSObject _) implements JSObject, CSSRule {
  external CSSOMString get name;
  external CSSStyleDeclaration get style;
}
extension type CSSNamespaceRule._(JSObject _) implements JSObject, CSSRule {
  external CSSOMString get namespaceURI;
  external CSSOMString get prefix;
}
extension type CSSStyleDeclaration._(JSObject _) implements JSObject {
  external CSSOMString get cssText;
  external set cssText(CSSOMString value);
  external int get length;
  external CSSRule? get parentRule;
  external CSSOMString get cssFloat;
  external set cssFloat(CSSOMString value);
  external CSSOMString getPropertyValue(CSSOMString property);
  external CSSOMString getPropertyPriority(CSSOMString property);
  external void setProperty(
    CSSOMString property,
    CSSOMString value, [
    CSSOMString priority,
  ]);
  external CSSOMString removeProperty(CSSOMString property);
}
extension type ElementCSSInlineStyle._(JSObject _) implements JSObject {
  external CSSStyleDeclaration get style;
  external StylePropertyMap get attributeStyleMap;
}
extension type CSS._(JSObject _) implements JSObject {}
external CSS get CSS;
