// Generated by Rampage on 2025-02-07 08:13:59.893264

import 'dart:js_interop';

import 'dom.dart';

extension type Performance._(JSObject _) implements JSObject, EventTarget {
  external DOMHighResTimeStamp get timeOrigin;
  external DOMHighResTimeStamp now();
  external JSObject toJSON();
}
typedef DOMHighResTimeStamp = double;
typedef EpochTimeStamp = int;
