// Generated by Rampage on 2025-02-07 08:14:00.179009

import 'dart:js_interop';

import 'dom.dart';
import 'geometry.dart';

extension type ResizeObserverOptions._(JSObject _) implements JSObject {
  external factory ResizeObserverOptions({ResizeObserverBoxOptions box});

  external ResizeObserverBoxOptions get box;
  external set box(ResizeObserverBoxOptions value);
}
typedef ResizeObserverBoxOptions = String;
typedef ResizeObserverCallback = JSFunction;
extension type ResizeObserver._(JSObject _) implements JSObject {
  external factory ResizeObserver(ResizeObserverCallback callback);

  external void observe(Element target, [ResizeObserverOptions options]);
  external void unobserve(Element target);
  external void disconnect();
}
extension type ResizeObserverEntry._(JSObject _) implements JSObject {
  external Element get target;
  external DOMRectReadOnly get contentRect;
  external JSArray<ResizeObserverSize> get borderBoxSize;
  external JSArray<ResizeObserverSize> get contentBoxSize;
  external JSArray<ResizeObserverSize> get devicePixelContentBoxSize;
}
extension type ResizeObserverSize._(JSObject _) implements JSObject {
  external double get inlineSize;
  external double get blockSize;
}
