// Generated by Rampage on 2025-02-07 08:14:00.215153

import 'dart:js_interop';

import 'dom.dart';
import 'html.dart';

extension type ProgressEventInit._(JSObject _) implements JSObject, EventInit {
  external factory ProgressEventInit({
    bool bubbles,
    bool cancelable,
    bool composed,
    bool lengthComputable,
    int loaded,
    int total,
  });

  external bool get lengthComputable;
  external set lengthComputable(bool value);
  external int get loaded;
  external set loaded(int value);
  external int get total;
  external set total(int value);
}
typedef XMLHttpRequestResponseType = String;
extension type XMLHttpRequestEventTarget._(JSObject _)
    implements JSObject, EventTarget {
  external EventHandler get onloadstart;
  external set onloadstart(EventHandler value);
  external EventHandler get onprogress;
  external set onprogress(EventHandler value);
  external EventHandler get onabort;
  external set onabort(EventHandler value);
  external EventHandler get onerror;
  external set onerror(EventHandler value);
  external EventHandler get onload;
  external set onload(EventHandler value);
  external EventHandler get ontimeout;
  external set ontimeout(EventHandler value);
  external EventHandler get onloadend;
  external set onloadend(EventHandler value);
}
extension type XMLHttpRequestUpload._(JSObject _)
    implements JSObject, XMLHttpRequestEventTarget {}
extension type XMLHttpRequest._(JSObject _)
    implements JSObject, XMLHttpRequestEventTarget {
  external factory XMLHttpRequest();

  external EventHandler get onreadystatechange;
  external set onreadystatechange(EventHandler value);
  external int get readyState;
  external int get timeout;
  external set timeout(int value);
  external bool get withCredentials;
  external set withCredentials(bool value);
  external XMLHttpRequestUpload get upload;
  external String get responseURL;
  external int get status;
  external String get statusText;
  external XMLHttpRequestResponseType get responseType;
  external set responseType(XMLHttpRequestResponseType value);
  external JSAny get response;
  external String get responseText;
  external Document? get responseXML;
  external void open(String method, String url);
  external void open(
    String method,
    String url,
    bool async, [
    String? username,
    String? password,
  ]);
  external void setRequestHeader(String name, String value);
  external void send([JSAny body]);
  external void abort();
  external String? getResponseHeader(String name);
  external String getAllResponseHeaders();
  external void overrideMimeType(String mime);
}
extension type FormData._(JSObject _) implements JSObject {
  external factory FormData([HTMLFormElement form, HTMLElement? submitter]);

  external void append(String name, String value);
  external void append(String name, Blob blobValue, [String filename]);
  external void delete(String name);
  external FormDataEntryValue? get(String name);
  external JSArray<FormDataEntryValue> getAll(String name);
  external bool has(String name);
  external void set(String name, String value);
  external void set(String name, Blob blobValue, [String filename]);
}
extension type ProgressEvent._(JSObject _) implements JSObject, Event {
  external factory ProgressEvent(
    String type, [
    ProgressEventInit eventInitDict,
  ]);

  external bool get lengthComputable;
  external int get loaded;
  external int get total;
}
typedef FormDataEntryValue = JSAny;
